<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="BPMN" nsURI="mde.org" nsPrefix="bpmn">
  <eClassifiers xsi:type="ecore:EClass" name="Object"/>
  <eClassifiers xsi:type="ecore:EClass" name="Process" eSuperTypes="#//Object">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Pool" eSuperTypes="#//Object">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Ref_Lane" lowerBound="1"
        upperBound="-1" eType="#//Lane" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SubProcess" eSuperTypes="#//Process"/>
  <eClassifiers xsi:type="ecore:EClass" name="Gateway" eSuperTypes="#//Object #//Flow"/>
  <eClassifiers xsi:type="ecore:EClass" name="Task" eSuperTypes="#//Object #//Process"/>
  <eClassifiers xsi:type="ecore:EClass" name="Flow">
    <eStructuralFeatures xsi:type="ecore:EReference" name="To" lowerBound="1" upperBound="-1"
        eType="#//Task"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="From" lowerBound="1" upperBound="-1"
        eType="#//Task"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Artifacts" eSuperTypes="#//Object"/>
  <eClassifiers xsi:type="ecore:EClass" name="Group" eSuperTypes="#//Artifacts"/>
  <eClassifiers xsi:type="ecore:EClass" name="DataObject" eSuperTypes="#//Artifacts"/>
  <eClassifiers xsi:type="ecore:EClass" name="TextAnnotation" eSuperTypes="#//Artifacts"/>
  <eClassifiers xsi:type="ecore:EClass" name="OR" eSuperTypes="#//Gateway"/>
  <eClassifiers xsi:type="ecore:EClass" name="XOR" eSuperTypes="#//Gateway"/>
  <eClassifiers xsi:type="ecore:EClass" name="Start" eSuperTypes="#//Event"/>
  <eClassifiers xsi:type="ecore:EClass" name="Join" eSuperTypes="#//Parallel"/>
  <eClassifiers xsi:type="ecore:EClass" name="Fork" eSuperTypes="#//Parallel"/>
  <eClassifiers xsi:type="ecore:EClass" name="Event" eSuperTypes="#//Object">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Parallel" eSuperTypes="#//Gateway"/>
  <eClassifiers xsi:type="ecore:EClass" name="MessageFlow" eSuperTypes="#//Flow">
    <eStructuralFeatures xsi:type="ecore:EReference" name="To_pool" lowerBound="1"
        upperBound="-1" eType="#//Pool"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Lane" eSuperTypes="#//Object">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Intermediate" eSuperTypes="#//Event"/>
  <eClassifiers xsi:type="ecore:EClass" name="End" eSuperTypes="#//Event"/>
</ecore:EPackage>
